#!/bin/bash
echo 'post-receive: Triggered.'
cd /home/pi/code/live/web
echo 'post-receive: git check out…'
git --git-dir=/home/pi/code/web.git --work-tree=/home/pi/code/live/web checkout master -f
echo 'post-receive: npm install…'
npm install \
&& echo 'post-receive: building…' \
&& npm run build \
&& echo 'post-receive: → done.' \
&& (pm2 delete 'web-by-githook' || true) \
&& pm2 start npm --name 'web-by-githook' -- run server \
&& echo 'post-receive: app started successfully with pm2.'